### ISSUE TITLE
Not working on iOS 9

### ISSUE THREAD

**Issue by MaKleSoft** [VersoSolutions/CordovaClipboard#16]
Anybody else having problems with iOS 9? There aren't any exceptions, the native plugin methods simply never gets called.

**Comment by kentmw** [comment]
Can anyone else verify this? I'm considering adopting this plugin for my project and this makes me nervous

**Comment by stevesum** [comment]
I use this plugin on iOS9 without any problem.

**Comment by MaKleSoft** [comment]
So it turned out that the plugin source files where just not included in the build for some reason. Removing and re-adding the files to the target solved the problem. Sorry for not following up on this!

**Comment by kentmw** [comment]
Thanks for the clarification.
