### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by whatnowangga** [VersoSolutions/CordovaClipboard#29]
hello
can you help me
i install this plugin to my ionic 2 project
and the result is like this
http://prntscr.com/fhxpts
http://prntscr.com/fhxq17

**Comment by BassamHabash** [comment]
hello @anggaand123 
you should do 
ionic plugin add https://github.com/VersoSolutions/CordovaClipboard
or
cordova plugin add https://github.com/VersoSolutions/CordovaClipboard

**Comment by WuglyakBolgoink** [comment]
@anggaand123 close ticket?

**Comment by elewin** [comment]
Try `cordova plugin add https://github.com/VersoSolutions/CordovaClipboard --nofetch`
