### ISSUE TITLE
Phonegap Build documentation question

### ISSUE THREAD

**Issue by JMarqz** [VersoSolutions/CordovaClipboard#5]
Visiting the <a href="https://build.phonegap.com/plugins/67">Phonegap Build Plugin Documentation</a> sends to here: https://github.com/VersoSolutions/CordovaClipboard/blob/941fd568ff924018a223a48f4e94c1d0a8d18e25/README.md

But I found this version that is newer and the documentations are different. Which one is correct for <b>Phonegap Build Plugin</b>? Thanks!

And another question, is necessary include explicitly the <b>phonegap.js</b> file into the index.html for the plugin works?

**Comment by ctrevisan** [comment]
You should use the latest version of the plugin, namely this one. I haven't tested it with Phonegap Build in a while but it should work.

Yes, AFAIK you need to explicitly include `phonegap.js` in your `index.html`file.

Let me know if you have any problems with the above.

**Comment by JMarqz** [comment]
Thanks for answer!

I already tested in Phonegap Build, but the latest version code doesn't work. For Phonegap Build works: `window.plugins.clipboard`. I think that you have don't updated the PGB plugin with the new code.

And just like a suggestion, you should add the instruction to add `phonegap.js` in the `index.html` in the <a href="https://github.com/VersoSolutions/CordovaClipboard/blob/941fd568ff924018a223a48f4e94c1d0a8d18e25/README.md">PGB plugin documentation</a>.

Thanks a lot, is a great plugin!
